# Generated by Django 2.2.18 on 2021-04-08 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210406_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrifile',
            new_name='UserProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 7, 35, 8, 262346, tzinfo=utc)),
        ),
    ]
